sudo: required
addons:
  apt:
    packages:
    - docker-ce
  sonarcloud:
    organization: "maraaghib-github"

language: python
python:
  - "3.5"

services:
  - docker

install:
  - cd Docker; docker-compose up -d --build; cd ..
  - pip3 install -r requirements.txt

script:
  - sleep 10
  - curl localhost:8100
  - cd tests; ./test.sh; cd ..
  - sonar-scanner

after_script:
  - cd Docker; docker-compose down -v --rmi all