sudo: required
addons:
  apt:
    packages:
    - docker-ce
  sonarcloud:
    organization: "gchupin-github" # the key of the org you chose at step #3

language: python
python:
  - "3.5"

services:
  - docker

install:
  - cd Docker; docker-compose up -d --build; cd ..

script:
  - curl localhost:8100
  - pwd
  - sonar-scanner

after_script:
  - docker-compose down -v --rmi all