
version: '3'

services:
    # Adminer (formerly phpMinAdmin) is a full-featured database management tool
    adminer:
        image: adminer
        container_name: adminer
        restart: always
        ports:
            - 8080:8080

    database:
        image: mysql:8.0.2
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: pass
            MYSQL_DATABASE: Cdp2018
            MYSQL_USER: admin
            MYSQL_PASSWORD: pass
        ports:
            - "9906:3306"
        volumes:
            - ./db:/var/lib/mysql:rw

    web:
        build:
            context: .
        container_name: phpPdo
        depends_on:
            - database
        volumes:
            - ../src/:/var/www/html/
        ports:
            - "8100:80"
        links:
            - database
volumes:
  mysql:
