
version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Cdp2018
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "9906:3306"
    volumes:
      - mysql:/var/lib/mysql

  web:
    build:
      context: .
    container_name: phpPdo
    depends_on:
      - mysql
    volumes:
      - ../src/php/:/var/www/html/
    ports:
      - "8100:80"
    links:
      - mysql
volumes:
  mysql:
